<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Security Check</title>
    <style>
      html {
	  font-family: "Lucida Grande", Verdana, Arial, sans-serif;
	  font-size: 62.5%;
      }
      body {
	  font-size: 1.2em;
	  margin: 16px 16px 0px 16px;
	  background: white;
      }
      h1, h2 {
	  font-family: "Gill Sans", Verdana, Arial, sans-serif;
	  color: #333;
	  margin: 0;
	  padding: 1.0em 0 0.15em 0;
      }

      h1 { font-size: 1.5em; border-bottom: 1px solid #ddd; }
      h2 { font-size: 1.3em; }

      div.error {
          border: solid red 1px;
          margin: 20px;
          padding: 10px;
      }

      div.example {
          border: solid #ddd 1px;
	  margin: 20px;
          padding: 10px;
      }

      pre {
	  font-size: 1.2em;
      }
    </style>
  </head>
  <body>
     <h1> Security Check </h1>

     <h2>
	You are attempting to access a secure section of this Gallery installation.  You can't
        proceed until you pass the security check.
     </h2>
