    As a security precaution, please enter your setup password to continue.

    <br><br>

    Your password is defined in your gallery/config.php file like this:

    <pre>$gallery->setConfig('setup.password', '<b>your password here</b>');</pre>

    <br><br>
    
    <form method="post">
    Password: 
    <input type="password" name="g2_password">
    <script type="text/javascript">document.forms[0]['g2_password'].focus();</script>
    <input type="submit" value="Go">
    </form>
