all:
	cd interfaces && $(MAKE) -$(MAKEFLAGS)
	cd GalleryStorage/DatabaseStorage/schema && $(MAKE) -$(MAKEFLAGS)

scrub:
	cd interfaces && $(MAKE) -$(MAKEFLAGS) scrub
	cd GalleryStorage/DatabaseStorage/schema && $(MAKE) -$(MAKEFLAGS) scrub

