ALTER TABLE DB_TABLE_PREFIXPluginParameterMap ADD COLUMN DB_COLUMN_PREFIXparameterValueTemp text;

UPDATE DB_TABLE_PREFIXPluginParameterMap SET DB_COLUMN_PREFIXparameterValueTemp = CAST(DB_COLUMN_PREFIXparameterValue AS text);

ALTER TABLE DB_TABLE_PREFIXPluginParameterMap DROP DB_COLUMN_PREFIXparameterValue;

ALTER TABLE DB_TABLE_PREFIXPluginParameterMap RENAME DB_COLUMN_PREFIXparameterValueTemp to DB_COLUMN_PREFIXparameterValue;

ALTER TABLE DB_TABLE_PREFIXPluginParameterMap ALTER DB_COLUMN_PREFIXparameterValue SET NOT NULL;



UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=3
  WHERE DB_COLUMN_PREFIXname='PluginParameterMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=2;


