CREATE TABLE DB_TABLE_PREFIXTkPropertyMap(
 DB_COLUMN_PREFIXname VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXtype VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXdescription VARCHAR(128) NOT NULL);
INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('TkPropertyMap', 1, 0);

