CREATE TABLE DB_TABLE_PREFIXChildEntity(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXparentId INTEGER NOT NULL
);
ALTER TABLE DB_TABLE_PREFIXChildEntity ADD PRIMARY KEY (DB_COLUMN_PREFIXid);
CREATE INDEX DB_TABLE_PREFIXChildEntity_52718 ON DB_TABLE_PREFIXChildEntity(DB_COLUMN_PREFIXparentId);
INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('ChildEntity', 1, 0);

