<p> <?php print _("Every Gallery will have at least one administrator user who has full access to view/modify everything. Please choose a username and password for your main administrator account. You can add additional users later.") ?> </p>

<form>
<table border="0">
<tr>
<td style="text-align: left;"><?php print _('Admin username:') ?></td>
<td><input type="text" value="<?php print _('admin') ?>" /></td>
</tr>
<tr>
<td style="text-align: left;"><?php print _('Password:') ?></td>
<td><input type="password" value="" /></td>
</tr>
<tr>
<td style="text-align: left;"><?php print _('(type again)') ?></td>
<td><input type="password" value="" /></td>
</tr>
</table>
</form>

<p>
<span class="bold" style="background-color: #d8d8d8; border: 1px solid #000000; padding: 3px;"><a href="index.php?step=5"><?php print _('Go to Step 5&rarr;') ?></a></span>
</p>
