<p>
<?php print _("Congratulations! Your Gallery2<span style=\"color:ae0000; font-style: italic;\">Alpha</span> has successfully installed! See... that wasn't so hard, was it? Now it's time to configure your gallery and upload some photos!") ?>
</p>

<p class="bold">
<?php print _("Now get me to my photos!") ?>
</p>

<p>
<span class="bold" style="background-color: #d8d8d8; border: 1px solid #000000; padding: 3px;"><a href="../main.php"><?php print _('Go to Gallery2') ?></a></span>
</p>
