<p>
<?php print _("This is where we would check to make sure that all your files have been uploaded properly and to the correct locations. But since this is only an alpha release, we'll assume you did just fine, so let's move right along until we get around to implementing this...") ?>
</p>

<p>
<span class="bold" style="background-color: #d8d8d8; border: 1px solid #000000; padding: 3px;"><a href="index.php?step=3"><?php print _('Go to Step 3&rarr;') ?></a></span>
</p>
