<p>
<?php print _("Getting Gallery installed on your webserver requires 7 steps. This installer will guide you through these steps and provide assistance along the way if additional steps are required to get your Gallery up and running. Once a step has been completed, you can go back and make changes at any time.") ?>
</p>

<p class="bold">
<?php print _("Let's Go!") ?>
</p>

<p>
<span class="bold" style="background-color: #d8d8d8; border: 1px solid #000000; padding: 3px;"><a href="index.php?step=1"><?php print _('Go to Step 1&rarr;') ?></a></span>
</p>
