CREATE TABLE DB_TABLE_PREFIXAlbumItem(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 DB_COLUMN_PREFIXtheme varchar(32),
 DB_COLUMN_PREFIXorderBy varchar(128),
 DB_COLUMN_PREFIXorderDirection varchar(32),
 PRIMARY KEY(DB_COLUMN_PREFIXid)
) TYPE=DB_TABLE_TYPE;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('AlbumItem', 1, 1);


