CREATE TABLE DB_TABLE_PREFIXTkPropertyMap(
 DB_COLUMN_PREFIXname varchar(128) NOT NULL,
 DB_COLUMN_PREFIXtype varchar(128) NOT NULL,
 DB_COLUMN_PREFIXdescription varchar(128) NOT NULL
) TYPE=DB_TABLE_TYPE;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('TkPropertyMap', 1, 0);


