CREATE TABLE DB_TABLE_PREFIXPluginMap(
 DB_COLUMN_PREFIXpluginType varchar(32) NOT NULL,
 DB_COLUMN_PREFIXpluginId varchar(32) NOT NULL,
 DB_COLUMN_PREFIXactive int(1) NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXpluginType, DB_COLUMN_PREFIXpluginId)
) TYPE=DB_TABLE_TYPE;
INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('PluginMap', 1, 1);

