ALTER TABLE DB_TABLE_PREFIXSchema
  ADD COLUMN DB_COLUMN_PREFIXtestCol varchar(128),
  ADD INDEX DB_TABLE_PREFIXSchema_18169(DB_COLUMN_PREFIXtestCol);

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='Schema' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;


