CREATE TABLE DB_TABLE_PREFIXSchema(
 DB_COLUMN_PREFIXname varchar(128) NOT NULL,
 DB_COLUMN_PREFIXmajor int(11) NOT NULL,
 DB_COLUMN_PREFIXminor int(11) NOT NULL,
 PRIMARY KEY(DB_COLUMN_PREFIXname)
) TYPE=DB_TABLE_TYPE;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('Schema', 1, 0);


