## mysql
# PermalinksMap
CREATE TABLE DB_TABLE_PREFIXPermalinksMap(
 DB_COLUMN_PREFIXaliasName varchar(128) NOT NULL,
 DB_COLUMN_PREFIXdestId int(11) NOT NULL,
 UNIQUE KEY(DB_COLUMN_PREFIXaliasName),
 INDEX DB_TABLE_PREFIXPermalinksMap_84225(DB_COLUMN_PREFIXdestId)
) TYPE=DB_TABLE_TYPE;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('PermalinksMap', 1, 0);

## postgres
# PermalinksMap
CREATE TABLE DB_TABLE_PREFIXPermalinksMap(
 DB_COLUMN_PREFIXaliasName VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXdestId INTEGER NOT NULL
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXPermalinksMap_3215 ON DB_TABLE_PREFIXPermalinksMap(DB_COLUMN_PREFIXaliasName);

CREATE INDEX DB_TABLE_PREFIXPermalinksMap_84225 ON DB_TABLE_PREFIXPermalinksMap(DB_COLUMN_PREFIXdestId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('PermalinksMap', 1, 0);

## oracle
# PermalinksMap
CREATE TABLE DB_TABLE_PREFIXPermalinksMap(
 DB_COLUMN_PREFIXaliasName VARCHAR2(128) NOT NULL,
 DB_COLUMN_PREFIXdestId INTEGER NOT NULL
);

CREATE INDEX DB_TABLE_PREFIXPermalinksMap_84225
   ON DB_TABLE_PREFIXPermalinksMap(DB_COLUMN_PREFIXdestId);

ALTER TABLE DB_TABLE_PREFIXPermalinksMap
 ADD UNIQUE (DB_COLUMN_PREFIXaliasName)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('PermalinksMap', 1, 0);

## db2
# PermalinksMap
CREATE TABLE DB_TABLE_PREFIXPermalinksMap(
 DB_COLUMN_PREFIXaliasName VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXdestId INTEGER NOT NULL
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXPerma66_3215  
 ON DB_TABLE_PREFIXPermalinksMap(DB_COLUMN_PREFIXaliasName);

CREATE INDEX DB_TABLE_PREFIXPerma66_84225
   ON DB_TABLE_PREFIXPermalinksMap(DB_COLUMN_PREFIXdestId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('PermalinksMap', 1, 0);

