CREATE TABLE DB_TABLE_PREFIXPluginMap(
 DB_COLUMN_PREFIXpluginType VARCHAR2(32) NOT NULL,
 DB_COLUMN_PREFIXpluginId VARCHAR2(32) NOT NULL,
 DB_COLUMN_PREFIXactive NUMBER(1) NOT NULL
);

ALTER TABLE DB_TABLE_PREFIXPluginMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXpluginType, DB_COLUMN_PREFIXpluginId)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('PluginMap', 1, 1);


