CREATE TABLE DB_TABLE_PREFIXFactoryMap(
 DB_COLUMN_PREFIXclassType VARCHAR2(128),
 DB_COLUMN_PREFIXclassName VARCHAR2(128),
 DB_COLUMN_PREFIXimplId VARCHAR2(128),
 DB_COLUMN_PREFIXimplPath VARCHAR2(128),
 DB_COLUMN_PREFIXimplModuleId VARCHAR2(128),
 DB_COLUMN_PREFIXhints VARCHAR2(255),
 DB_COLUMN_PREFIXorderWeight VARCHAR2(255));

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FactoryMap', 1, 0);


