ALTER TABLE DB_TABLE_PREFIXSchema
  ADD (DB_COLUMN_PREFIXtestCol VARCHAR2(128))CREATE INDEX DB_TABLE_PREFIXSchema_80114
  ON DB_TABLE_PREFIXSchema(DB_COLUMN_PREFIXtestCol, DB_COLUMN_PREFIXSTRING, DB_COLUMN_PREFIXMEDIUM)
;

UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='Schema' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;


