ALTER TABLE DB_TABLE_PREFIXQuotasMap
  DROP INDEX DB_TABLE_PREFIXQuotasMap_48775,
  MODIFY COLUMN DB_COLUMN_PREFIXuserOrGroupId int(11) NOT NULL,
  ADD PRIMARY KEY(DB_COLUMN_PREFIXuserOrGroupId);
UPDATE DB_TABLE_PREFIXSchema
  SET DB_COLUMN_PREFIXmajor=1, DB_COLUMN_PREFIXminor=1
  WHERE DB_COLUMN_PREFIXname='QuotasMap' AND DB_COLUMN_PREFIXmajor=1 AND DB_COLUMN_PREFIXminor=0;

